### ISSUE TITLE
Loss function in ContentDis

### ISSUE THREAD

**Issue by ZJYang-SZU** [imlixinyang/AGUIT#1]
Hi，why out1 was not used in either dis or gen loss function

**Comment by imlixinyang** [comment]
Thank you very much to notice this mistake. I'll correct it later. You can also follow the paper to correct it by yourself! 
By the way, I'll release the code of another work of mine recently, with scalibity and **controllable** diversity. Please look forward to it if you're interested in this area!

**Comment by imlixinyang** [comment]
I have corrected this problem. Thank you@ZJYang-SZU a lot for providing this issue.
